---
default:
    image: "python:3.8"
    before_script:
        - export PIP_CACHE_DIR="$(pwd)/.pip-cache"
        - pip3 install 'tox < 3.15'

variables:
    CPE_LOGLEVEL: DEBUG
    TOXENV: ${CI_JOB_NAME}
    PIP_DISABLE_PIP_VERSION_CHECK: 1

.job_template: &job_template
    script:
        - tox
    artifacts:
      paths:
        - .pip-cache/
        - .tox/
      expire_in: 1 week

validate:
  stage: test
  extends: .job_template

docs:
  stage: test
  extends: .job_template
  artifacts:
    paths:
      - build/docs
      - .pip-cache/
      - .tox/

#run:
#    stage: deploy
#    extends: .job_template

pages:
  stage: deploy
  extends: .job_template
  needs:
    - job: docs
      artifacts: true
  after_script:
    - printf "Published to ${CI_PAGES_URL}\n"
  artifacts:
    paths:
      - public
  only:
    refs:
      - master
