---
default:
    image: "python:3.8"
    before_script:
        - pip3 install 'tox < 3.15'

variables:
    CPE_LOGLEVEL: DEBUG
    TOXENV: ${CI_JOB_NAME}
    PIP_DISABLE_PIP_VERSION_CHECK: 1

.job_template: &job_base
    script:
        - tox

validate:
  stage: test
  extends: .job_template

#run:
#    stage: deploy
#    extends: .job_template
